# Generated by Django 4.2.5 on 2024-03-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=1000)),
                ('lastname', models.CharField(max_length=1000)),
                ('age', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
            ],
        ),
    ]
